# Generated by Django 6.0.3 on 2026-03-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('poids', models.FloatField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
