# Generated by Django 6.0.3 on 2026-03-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedition',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='poids',
        ),
        migrations.AddField(
            model_name='expedition',
            name='client_email',
            field=models.EmailField(default='client@transport.com', max_length=254),
        ),
        migrations.AddField(
            model_name='expedition',
            name='client_nom',
            field=models.CharField(default='Client inconnu', max_length=120),
        ),
        migrations.AddField(
            model_name='expedition',
            name='date_maj',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expedition',
            name='destination',
            field=models.CharField(default='Destination inconnue', max_length=200),
        ),
        migrations.AddField(
            model_name='expedition',
            name='origine',
            field=models.CharField(default='Origine inconnue', max_length=200),
        ),
        migrations.AddField(
            model_name='expedition',
            name='poids_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='expedition',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='reference',
            field=models.CharField(default='EXP-0000', max_length=30, unique=True),
        ),
    ]
