# Generated by Django 6.0.3 on 2026-03-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_expedition_options_remove_expedition_poids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='annee',
            field=models.PositiveSmallIntegerField(db_index=True, default=2026, editable=False),
        ),
        migrations.AddField(
            model_name='expedition',
            name='numero',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['annee', 'numero'], name='transport_e_annee_f4c66b_idx'),
        ),
    ]
