# Generated by Django 6.0.3 on 2026-03-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_trackingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='date_cible',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
