# Generated by Django 6.0.3 on 2026-03-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_expedition_date_cible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(blank=True, default='', max_length=50)),
                ('modele', models.CharField(blank=True, default='', max_length=50)),
                ('capacite_kg', models.PositiveIntegerField(default=1000)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MISSION', 'En mission'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], db_index=True, default='PLANIFIEE', max_length=20)),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
                ('expedition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='transport.expedition')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='transport.vehicule')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
