# Generated by Django 6.0.3 on 2026-03-05 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_vehicule_livraison'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expedition',
            name='dropoff_adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expedition',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expedition',
            name='pickup_adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expedition',
            name='planifiee_pour',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='expedition',
            name='raison_annulation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expedition',
            name='type_colis',
            field=models.CharField(choices=[('DOCUMENTS', 'Documents'), ('COLIS', 'Colis'), ('FRAGILE', 'Fragile'), ('ALIMENTAIRE', 'Alimentaire'), ('AUTRE', 'Autre')], db_index=True, default='COLIS', max_length=20),
        ),
    ]
