# Generated by Django 6.0.3 on 2026-05-26 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_model_defaults_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_livraisons', to=settings.AUTH_USER_MODEL)),
                ('expedition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='transport.expedition')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=120)),
                ('corps', models.TextField()),
                ('lu_staff', models.BooleanField(db_index=True, default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_client', to='transport.expedition')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('EN_ATTENTE', "En attente d'assignation"), ('LIVRAISON_PLANIFIEE', 'Livraison planifiée'), ('EN_COURS', 'Livraison en cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée'), ('MESSAGE_CLIENT', 'Message client'), ('AVIS_CLIENT', 'Avis client'), ('CONFIRMATION', 'Confirmation requise'), ('SYSTEME', 'Système')], db_index=True, max_length=30)),
                ('titre', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, default='', max_length=255)),
                ('lu', models.BooleanField(db_index=True, default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transport.expedition')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
